name: Python Security Check with Bandit

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  bandit-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit security checks
        continue-on-error: true
        run: bandit -r ./yirabot